config/routes.rb
Rails.application.routes.draw do
 resources :questions
 # resources :questions, only: %i[index new edit create update destroy show]
 # get "/questions", to: 'questions#index'
 # get "/questions/new", to: 'questions#new'
 # get "/questions/:id/edit", to: 'questions#edit'
 # post "/questions", to: 'questions#create'

  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
    validates :title, presence:true, length:{minimum:2}
    validates :body, presence:true, length:{minimum:2}

    def formatted_created_at
      created_at.strftime('%Y-%m-%d %H:%M:%S')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @name = params[:name]
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
   def show
        @question = Question.find_by id: params[:id]
   end
   def destroy
      @question = Question.find_by id: params[:id]
      @question.destroy
      redirect_to questions_path
   end
   def edit
      @question = Question.find_by id: params[:id]
    end

   def update
      @question = Question.find_by id: params[:id]
      if @question.update question_params
        redirect_to questions_path
      else
        render :new
      end
   end

    def index
      @questions = Question.all
    end

    def new
        @question = Question.new
    end

    def create
        puts params.inspect
        #render plain: params
        @question = Question.new question_params
        if @question.save
            redirect_to questions_path
        else
            render :new
        end
    end

    def question_params
        params.require(:question).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Questions</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", media:"all","data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <header class='bg-dark text-white'>
      <div class="container">
           <nav class="navbar navbar-expand-lg">
             <div class="container-fluid">
               <%= link_to 'Let It Ask', root_path, class:'nav-link navbar-brand text-white' %>
               <div class="collapse navbar-collapse" id="navbarNav">
                 <ul class="navbar-nav">
                   <li class="nav-item">
                    <%= link_to 'Home', root_path, class:'nav-link text-white' %>
                   </li>
                   <li class="nav-item">
                    <%= link_to 'Questions', questions_path, class:'nav-link text-white' %>
                   </li>
                 </ul>
               </div>
             </div>
           </nav>
       </div>
  </header>
     <main>
         <%= yield %>
     <main>
     &copy; @antoninasych <%= Time.now.year %>
  </body>
</html>

app/views/pages/index.html.erb
<h1> Wellcome to Questionier </h1>

&copy; @antoninasych <%= Time.now.year%>

app/views/questions/_form.html.erb
<%=form_with(model: @question, data: { turbo: false }) do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title, required:true, minlength:2, placeholder: "Titile" %>
    <div>
    <div>
        <%= f.label :body %>
        <%= f.text_area :body, required:true, minlength:2, placeholder: "Body" %>
    <div>
 <%= f.submit "Submit Question" %>
<% end %>

app/views/questions/edit.html.erb
<h1>Update question</h1>
 <%= render 'form' %>

app/views/questions/index.html.erb
<h1> Questions </h1>

<%= @questions.each do |question| %>

<article class='card'>
    <div class='card-body'>
        <h2><%= question.title %></h2>

        <section class = 'card-text'>
         <small>  <time datetime="<%=question.formatted_created_at %>">   <%= question.formatted_created_at %></time></small>
            <div class='my-2'><%= question.body %>
            <br>
            <%= link_to 'Show', question_path(question), class:'btn btn-primary' %>
            <%= link_to 'Edit', edit_question_path(question), class:'btn btn-secondary' %>
            <%= link_to 'Destroy', question_path(question), data: {method: :delete, confirm: 'Are you sure?'}, class:'btn btn-danger'  %>
            </div>
        <section>
    <div>
</article>
<% end %>

app/views/questions/new.html.erb
<h1>New question</h1>
 <%= render 'form' %>

app/views/questions/show.html.erb
<h1> <%= @question.title %> </h1>


<h2><%= @question.title %></h2>
<time datetime="<%=@question.formatted_created_at %>">
<%= @question.formatted_created_at %></time>
<p><%= @question.body %>
<br>
<%= link_to 'Show', question_path(@question) %>
|
<%= link_to 'Edit', edit_question_path(@question) %>
|
<%= link_to 'Destroy', question_path(@question), data: {method: :delete, confirm: 'Are you sure?'}  %>
</p>

&copy; @antoninasych <%= Time.now.year %>